### ISSUE TITLE
[Testing Session] Bug Reports

### ISSUE THREAD

**Issue by KylusheL** [swsnu/swpp2021-team13#78]
간단한 피드백입니다.

사이트 자체의 아이디어가 참신하고 간단하고, 실제로 심심할 때 사람들과 함께 사용하기 좋은 것 같습니다.
DB가 날아간 부분 빼고 피드백을 드리면

1. 먼저 새로고침을 눌렀을 때 로그아웃이 되더니 모든 problem set이 사라집니다.
2. 문제 셋 추천버튼을 클릭했을 때 버튼만 없어지고 추천수가 올라가지 않습니다. (나중에 업데이트되는 듯합니다.)
3. Go Result를 눌렀을 때 렌더링이 되는 동안 잠시 not found가 표시됩니다.
4. Title이  'New Problem Set Title'이 그대로 표시되는 경우가 확인되었습니다.

만드느라 수고하셨습니다!

**Comment by TLB-MISS** [comment]
피드백 감사합니다!
